### ISSUE TITLE
Suggestion: `merge` shouldn't be a method

### ISSUE THREAD

**Issue by thephoenixofthevoid** [wavebeem/bread-n-butter#21]
The following method:
```
merge<A, B>(a: ActionResult<A>, b: ActionResult<B>): ActionResult<B>
```
at https://github.com/wavebeem/bread-n-butter/blob/c137393b74563c213f1eca0a70810a181df835b5/src/bread-n-butter.ts#L504
should be considered as a free function instead.

Reason: 
1. It doesn't depend on `this`.
2. It might be interpreted as `merging of contexts`, which it doesn't seem to be.
3. From a semantic point of view, it has nothing to do with a context directly.

**Comment by wavebeem** [comment]
1. This is true, but it's only useful if you're managing context directly. It was originally a free function, but I think it's more "hidden" this way since you will rarely need it.

2. That's fair. I considered naming it `mergeActionResults` but that's very wordy.

3. Same thought as point 1.

This is a good observation, but I've tried it both wise and I like how this reads better.

**Method**

```ts
function multiply(
  parser1: bnb.Parser<number>,
  parser2: bnb.Parser<number>
): bnb.Parser<number> {
  return new bnb.Parser<number>((context) => {
    const result1 = parser1.action(context);
    if (result1.type === "ParseFail") {
      return result1;
    }
    context = context.moveTo(result1.location);
    const result2 = context.merge(result1, parser2.action(context));
    if (result2.type === "ParseFail") {
      return result2;
    }
    context = context.moveTo(result2.location);
    const value = result1.value * result2.value;
    return context.merge(result2, context.ok(context.location.index, value));
  });
}
```

**Free Function**

```ts
function multiply(
  parser1: bnb.Parser<number>,
  parser2: bnb.Parser<number>
): bnb.Parser<number> {
  return new bnb.Parser<number>((context) => {
    const result1 = parser1.action(context);
    if (result1.type === "ParseFail") {
      return result1;
    }
    context = context.moveTo(result1.location);
    const result2 = bnb.mergeResults(result1, parser2.action(context));
    if (result2.type === "ParseFail") {
      return result2;
    }
    context = context.moveTo(result2.location);
    const value = result1.value * result2.value;
    return bnb.mergeResults(result2, context.ok(context.location.index, value));
  });
}
```

In particular what I like about the method approach is that custom parsers are all about using context methods.

**Comment by thephoenixofthevoid** [comment]
It's not a binary thing (more than 2 options exist). 

Just as an example. You may use second argument in Parser#constructor to contain such internal functions:
```js
function multiply(
  parser1: bnb.Parser<number>,
  parser2: bnb.Parser<number>
): bnb.Parser<number> {
  return new bnb.Parser<number>((context, { merge }) => {
    const result1 = parser1.action(context);
    if (result1.type === "ParseFail") {
      return result1;
    }
    context = context.moveTo(result1.location);
    const result2 = merge(result1, parser2.action(context));
    if (result2.type === "ParseFail") {
      return result2;
    }
    context = context.moveTo(result2.location);
    const value = result1.value * result2.value;
    return merge(result2, context.ok(context.location.index, value));
  });
}
```
I need some time to think about it, actually. I will write when I got new ideas.

**Comment by thephoenixofthevoid** [comment]
Regarding the second point in recent comment. This piece of code:
```
        if (result.location.index === context.location.index) {
          throw new Error(
            "infinite loop detected; don't call .repeat() with parsers that can accept zero characters"
          );
        }
```
made me think that actually `result` and `context` are actually the same object from two different perspectives. And for some reason we don't treat it as such, rather converting back-and-forth all the time. My point is to somehow unify these two.

**Comment by thephoenixofthevoid** [comment]
Also I just found out the following way to refactor `and` combinator, that supports my point:
```ts
  and<B>(parserB: Parser<B>): Parser<[A, B]> {
    return new Parser((context) => {
      //---------------------------------------
      const a = this.action(context);
      if (a.type === ActionResultType.Fail) {
        return a;
      }
      context = context.moveTo(a.location);
      //---------------------------------------

      //---------------------------------------
      const b = merge(a, parserB.action(context))
      if (b.type === ActionResultType.Fail) {
        return b;
      }
      context = context.moveTo(b.location);
      //---------------------------------------

      const value: [A, B] = [a.value, b.value];
      return merge(b, context.ok(b.location.index, value))
    });
  }
```
Here I visually marked these `exec`s

**Comment by wavebeem** [comment]
I definitely originally had `context` include the value, but there was some reason I separated them. I can't remember exactly why I did it, to be honest.

**Comment by thephoenixofthevoid** [comment]
Here is more:
```ts
and<B>(parserB: Parser<B>): Parser<[A, B]> {
    return new Parser((context) => {
      //---------------------------------------
      const a = this.action(context);
      if (a.type === ActionResultType.Fail) {
        return mergeAll(a);
      }
      context = context.moveTo(a.location);
      //---------------------------------------

      //---------------------------------------
      const b = parserB.action(context)
      if (b.type === ActionResultType.Fail) {
        return mergeAll(a, b);
      }
      context = context.moveTo(b.location);
      //---------------------------------------

      const value: [A, B] = [a.value, b.value];
      const c = context.ok(b.location.index, value)
      return mergeAll(a, b, c);
    });
  }
```
where
```ts
function mergeAll(...rest: ActionResult<any>[]): ActionResult<any> {
  return rest.reduce(merge)
}
```
That looks even more interesting, like we may collect reports inside context during evaluation.

**Comment by wavebeem** [comment]
It's a little imperative, but I prefer reassigning `context` repeatedly so you don't "forget" about anything that happened along the way inside your custom parser

**Comment by thephoenixofthevoid** [comment]
That's a good point and I actually got it: giving examples both within the framework of this approach and not using it. In the latter case, you obviously need to store `.value` before `ctx` get rewritten. When using separate identifiers, no such problem arises.

**Comment by wavebeem** [comment]
True, but that's only an issue if you merge context and action result into a single class. With my current approach, the action results still have variable names.

**Comment by thephoenixofthevoid** [comment]
Yeah, I edited my message to include this note actually. I am trying now actually to figure out the underlying structure, that better suits: searching for blocks, which are always executed as a single unit. 
The actual code style may vary and be whatever you find preferable.

**Comment by thephoenixofthevoid** [comment]
So the observation here:
1) In most cases after .action goes the check for failed action
2) Reports within a parser are always merged from the first to last available, if parsers are meant to run as a sequence.
3) Changing value to a computed result can be considered as a separate report that should be treated the way results of parse actions are treated.

**Comment by thephoenixofthevoid** [comment]
Here is a little present:
```ts
export function all<A extends any[]>(...parsers: ManyParsers<A>): Parser<A> {
  return new Parser((context) => {
    var reports: ActionOK<A>[] = []
  
    for (let parser of parsers) {
        const report = parser.action(context);
        if (report.type === ActionResultType.Fail) 
          return mergeAll(...reports, report)
        reports.push(report);
        context = context.moveTo(report.location);
    }

    const values = reports.map(result => result.value)
    const last = context.ok(context.location.index, values)
    return mergeAll(...reports, last);
  });
}
```
Easy to read fast implementation of `.all`, based on what I've described so far

**Comment by thephoenixofthevoid** [comment]
And here comes `merge` again: 
```ts

/**
* Merge two sequential `ActionResult`s so that the `expected` and location data
* is preserved correctly.
*/
function merge<A, B>(a: ActionResult<A>, b: ActionResult<B>): ActionResult<B> {
  if (a.furthest.index > b.furthest.index) return {
    ...b,
    expected: a.expected,
    furthest: a.furthest
  }

  if (a.furthest.index < b.furthest.index) return {
    ...b,
    expected: b.expected,
    furthest: b.furthest
  }

  return {
    ...b,
    expected: [...new Set([...a.expected, ...b.expected])],
    furthest: a.furthest
  }
}
```

**Comment by wavebeem** [comment]
If you're interested in adding optimized implementations for `all` and `choice` please open separate PRs for those.

The topic at hand here is "`merge` shouldn't be a method". I totally see your point, and that's how I initially implemented it, but I changed it for the reasons I laid out here.

Whether `ActionOK<A> | ActionFail` should be merged together with `Context` is somewhat related to the topic, but I'm still skeptical on that.

`Context` is just "where you are" + "what is the input" + a few helpers. And is ultimately 100% in service of `new bnb.Parser(custom)`.

`ActionOK<A>` and `ActionFail` contain several fields that are totally irrelevant to custom parser construction, so I'd like to keep them separate for now.
