### ISSUE TITLE
Line number shouldn't increment until after `\n`

### ISSUE THREAD

**Issue by wavebeem** [wavebeem/bread-n-butter#34]
- `\n` should probably be considered as part of the current line. Only the next character should advance the line number.

https://github.com/jneen/parsimmon/issues/331

**Comment by hillin** [comment]
>\n should probably be considered as part of the current line. Only the next character should advance the line number.

I'm expecting this to happen!

> .node should be inclusive of the end, not exclusive. Will need some new kind of combinator like lastIndex, if possible

Just to reiterate what was said in the issue referenced above, I still don't think inclusive range is a good idea (almost all Range implementations have exclusive end index).

**Comment by wavebeem** [comment]
If you want to work on a PR feel free. I haven't been actively developing bnb for a while, but it is `0.x` so I can release breaking changes if need be lol

**Comment by hillin** [comment]
I tried to create a PR but then I realized bnb **does not** have the same behavior as Parsimmon. bnb handles `\n` exactly as I wanted, line number does not increment until after it.

The same old example:
```typescript
// parsimmon:
const parser = P.seqMap(P.index, P.digits, P.index, function (start, value, end) {
  console.log(start, value, end);
  return value;
});

parser.parse('1234\n');
// => {offset: 0, line: 1, column: 1} '1234' {offset: 4, line: 2, column: 0}

// bnb:
const parser = bnb.all(bnb.match(/\d+/).node('num'), bnb.text('\n').node('newline'));
console.log(parser.parse('1234\n').value[0]);
// =>{"type":"ParseNode","name":"num","value":"1234","start":{"index":0,"line":1,"column":1},"end":{"index":4,"line":1,"column":5}}
```

So apparently this issue does not exist in bnb at all.

**Comment by wavebeem** [comment]
Turns out I don't even remember how my own library works lol. Well that's great! I suppose I'll close the issue then.

Internal bnb code to handle line/col info:
https://github.com/wavebeem/bread-n-butter/blob/main/src/bread-n-butter.ts#L455-L472

![image](https://user-images.githubusercontent.com/176815/146425437-21f1e5b2-5a3a-4ec3-8824-9149590e78f1.png)
